### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by norlover** [JustinAzoff/flow-indexer#15]
Can you give me an example_config.json that handles pcap?
include Query API and Search

**Comment by JustinAzoff** [comment]
Hi!  I have example configuration here that works with gotm:

https://github.com/JustinAzoff/gotm/blob/master/deploy/flow-indexer.cfg

This expects pcap files to be named like

pcaps/2017/08/29/2017-08-29T17-50-58.pcap

If yours are named differently you'll need a slightly different configuration file.

**Comment by norlover** [comment]
thank you very much
