### ISSUE TITLE
search fails quietly

### ISSUE THREAD

**Issue by JonZeolla** [JustinAzoff/flow-indexer#4]
If you run a search against flow-indexer, and one of the files that are returned by the query fails to properly match the format provided in your `filename_to_time_regex`, flow-indexer will stop outputting results without giving an error message.  I found this because it appeared that I was getting a limited number of files in response to my queries, and when I made a query that should match every log, I only got a subset of sequential logs that stopped at a specific date.  I did troubleshooting by leveraging `stats` queries, which does properly fail with a helpful error message.

Happy to provide more details, if necessary.  Chatted with @JustinAzoff in the #bro IRC channel about this on 2017-07-07.

**Comment by JustinAzoff** [comment]
This is weird.. 

I see how there would be an error for /stats, but /search doesn't use `filename_to_time_regex`.

Was there an error being output to the server stderr?

I'll work on fixing /stats though.

**Comment by JustinAzoff** [comment]
Should be fixed in c47527a9e1e2581d1bf92d2433f187e87e363dd6

**Comment by JonZeolla** [comment]
I'm able to fix it by renaming the key/values in leveldb, or drop the entries entirely.  Below is what I see when hitting the API.
```
$ curl -s "12.34.56.78:8088/stats?i=conn&q=<subnet>"
filename_to_time_regex did not match "/path/to/bro/2018-07-07/conn.2018-07-07-15-00-00.14:45:05-16:10:06.log.gz"
$ curl -s "12.34.56.78:8088/search?i=conn&q=<subnet>" | wc -l
21810
$ curl -s "12.34.56.78:8088/search?i=conn&q=<subnet>" 1> /dev/null
$ echo $?
0
```

No stderr when doing the search that is truncated at 21810 conn logs due to hitting some sort of issue.  Earlier today that same query reported 3420 logs, but I've been working through the "filename_to_time_regex" errors.  As I fix them, my /search comes back with more results.

**Comment by JonZeolla** [comment]
I hit another issue today when doing some testing.  I have a known bad file which is getting indexed which I wanted to get rid of entirely (instead of just renaming).  I tried my luck to see if just ignorantly dropping the two related entries you told me about in leveldb would work, but that seems to break search queries from the date of that file until the end of the index (in my case, the end of the month).  Again, the search query doesn't seem to inform me that there are any issues, it just stops giving results for the rest of that month and moves on to the next one.

**Comment by JustinAzoff** [comment]
Ah, I found the bug causing errors to be ignored, so now you should get a proper error message when trying to do a search.

It may be better to ignore errors in this case, as failing with an error is only a little more helpful to you than failing without an error.

If that's what you want, then bitsetToDocs in leveldb store would just need to be changed from

    return docs, err

when it runs into an error, to just log the error and `continue`

**Comment by JustinAzoff** [comment]
With f221c3c608fcc6c7e4f7265445f9dfafd88d9553 most of the issues with searches failing should be fixed.  I still need to add some tooling for removing/renaming documents, but that's a separate issue.
